### PR TITLE
Add example for GNsearch of geocoding Lancaster

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Gone stale

**Comment by barryrowlingson** [comment]
If you can spritz some air freshener on it then it might be worth adding...

**Comment by Robinlovelace** [comment]
If only I could translate that metaphor into code... Next best thing: translate into a button press hehe.

**Comment by sckott** [comment]
@barryrowlingson been since nov. last year, thoughts

**Comment by julievdh** [comment]
Can you give an example of how to enter username in GNsearch? I've registered on the website

**Pull request merged**
